items:
- name: Visual Studio Tools for Docker
  href: /dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker?toc=/visualstudio/docker/toc.json&bc=/visualstudio/docker/breadcrumb/toc.json
  items:
  - name: 快速入门：Visual Studio Tools for Docker
    href: docker-tools.md
  - name: 在本地 Docker 容器中调试应用
    href: ../docker/vs-azure-tools-docker-edit-and-refresh.md
  - name: 使用 Visual Studio 将 ASP.NET 容器部署到容器注册表
    href: ../docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md
  - name: 使用 VirtualBox 配置 Docker 主机
    href: ../docker/vs-azure-tools-docker-setup.md
  - name: 排查使用 Docker 进行 Visual Studio 2017 开发的问题
    href: ../docker/vs-azure-tools-docker-troubleshooting-docker-errors.md
  expanded: true
ms.openlocfilehash: 0d476d43454bdbba18ce3dba8baffab1108e4250
ms.sourcegitcommit: c0202a77d4dc562cdc55dc2e6223c062281d9749
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 01/24/2019
ms.locfileid: "54874702"
